columns:
    Main_Current:
        rename: Current
        unit: amp
    Main_Voltage:
        rename: Voltage
        unit: volt
    Test_Time:
        rename: Test Time
        unit: second
    Ambient_Temperature:
        new_name: Temperature
        unit: celsius
    Step Time:
        unit: other
    Step_Index:
        rename: Step Index
metadata:
    Start Time: 1659044022000